language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-jersey-angular' ]; then cd .. && eval "mv $currentfolder generator-jersey-angular" && cd generator-jersey-angular; fi

